# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - main

pr: none

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '3e4a95aa-a0e7-4c66-bfcf-2e042ccaedb8'
  imageRepository: 'project'
  containerRegistry: 'project21backenddev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  AzureKeyVaultName: 'project-21-key-vault'
  AzureResourceGroupName: 'Project-21'
  tag: '43'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: project-21-backend-pool
    steps:
    # - script: docker system prune -a -f

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: $(subscriptionId)
        KeyVaultName: 'project-21-key-vault'
        SecretsFilter: '*'


    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        arguments: >
          --build-arg DATABASE_URL="$(DATABASEURL)"
          --build-arg FRONTEND_URL="$(FRONTENDURL)"
          --build-arg MAIL_HOST="$(MAILHOST)"
          --build-arg MAIL_USER="$(MAILUSER)"
          --build-arg MAIL_PASS="$(MAILPASS)"
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: $(subscriptionId)
        appName: 'project-21-backend-dev'
        containers: 'project21backenddev.azurecr.io/project:43'