# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '3e4a95aa-a0e7-4c66-bfcf-2e042ccaedb8'
  imageRepository: 'project'
  containerRegistry: 'project21backenddev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '43'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: project-21-backend-pool
    steps:
    - script: docker system prune -a -f

    - task: AzureCLI@2
      displayName: 'Allow agent IP'
      inputs:
        azureSubscription: 'Azure subscription 1(0839a5ee-329a-4b35-82c1-7c70e55542eb)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Get the agent's public IP
          ip=$(curl -s http://ipinfo.io/json | jq '.ip' | tr -d '"')

          # Add the IP to the Key Vault network rule
          az keyvault network-rule add \
            --name "$(AzureKeyVaultName)" \
            --resource-group "$(AzureResourceGroupName)" \
            --ip-address $ip

          # Set the IP as a pipeline variable
          echo "##vso[task.setvariable variable=agentIP]$ip"

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Azure subscription 1(0839a5ee-329a-4b35-82c1-7c70e55542eb)'
        KeyVaultName: 'project-21-key-vault'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: Docker@2
      displayName: Build image
      env:
        DATABASE_URL: $(DATABASEURL)
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        arguments: --build-arg DATABASE_URL=$(DATABASE_URL)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure subscription 1(0839a5ee-329a-4b35-82c1-7c70e55542eb)'
        appName: 'project-21-backend-dev'
        containers: 'project21backenddev.azurecr.io/project:43'